### ISSUE TITLE
Blogdown yaml considerations

### ISSUE THREAD

**Issue by apreshill** [r-lib/ymlthis#1]
Hey @malcolmbarrett,

I'm still so pumped about this package after the demo last week, and I applaud your herculean effort to include blogdown yaml here. Some considerations based on my experiences working with Hugo yamls:

1. I think [yml_blogdown.R](https://github.com/rstudio-education/ymlthis/blob/master/R/yml_blogdown.R) needs an `archetype` argument that defaults to `post`. This at least matches the new post addin in blogdown, but still not perfect (i.e., the hugo future imperfect theme uses [blog instead](https://github.com/jpescador/hugo-future-imperfect/blob/master/archetypes/blog.md)- I guess the tough thing is these could be ANYTHING, they are user-defined and therefore theme dependent). If no archetypes are present (would be weird but can happen), the default is to just return only the predefined content. Which leads me to...

1. There are two types of front matter: [predefined](https://gohugo.io/content-management/front-matter/#predefined) (which you have) and [user-defined](https://gohugo.io/content-management/front-matter/#user-defined) (tougher). It would be awesome if there was a way to pull yaml options from your theme's archetypes (so if I picked `post` as the archetype, these are my yaml options from the [academic theme](https://github.com/gcushen/hugo-academic/blob/master/archetypes/post/index.md)). A few things to keep in mind here:
    - Some of these may clobber the predefined fields- you don't want duplicate `date` fields for example or you'll get an error and with lengthy yaml files the duplicate fields are hard to find (hey- enhancement idea with IDE support is to highlight duplicate yaml fields!)
    - The presence of the `""` and `[]` in the yaml values is critical to preserve for the theme to work properly
    - The `#` comments (if present) are hugely helpful but tough sometimes to assume what bit they refer to (the academic theme author leaves a blank line between the yaml "chunks")

All this leads me to thinking that perhaps what is needed is improvements to the blogdown new post addin, because it uses the archetype specified from the theme but it strips the `""`, `[]`, and `#`. 

Maybe the ymlthis package could (a) add in the predefined front matter content, (b) dump the full batch of archetype-specific yaml all at once (instead of piece by piece) since there is typically no line by line documentation present, then (c) sweep out the duplicate fields (keeping the archetype over the predefined one to preserve comments).

Anyway, sorry for burdening you with all this! Curious to hear what you think.

**Comment by malcolmbarrett** [comment]
Thanks so much for laying this out @apreshill! This is *so* helpful.

So, let me tell you how ymlthis handles a few of these issues already. 

1. custom YAML: this one is tough because there are loads of ways to add new YAML fields. It's possible that our idea for a YAML field registry function will help, but in general, how I am handling it is via the `yml_toplevel()` function (name suggestions welcome on this one :p). This simply takes a named field and tacks it on. I'm also thinking about adding `...` to basically every `yml_*()` function that does that as well.

2. Duplicate fields: The approach I've taken is inspired by ggplot. It's bottom up: if there is a duplicate field, the most recent one takes precedence, so only one ends up in the actual YAML. I think I'm also going to add a warning about it, as ggplot does, adding something like `warn_if_duplicate_fields()` to each function.

3) Empty fields: Again inspired by ggplot, I have a function `yml_blank()` that sweeps out fields because I wanted both `NULL` and empty fields to be taken literally (`field: null` and `field: ""`, for example), so that will extend with relative ease.

After thinking about this a couple of days, here's where I'm leaning in general. `yml_blogdown_opts()` should catch and document those predefined Hugo fields as it currently does. For archetypes, I'm thinking of taking the approach pkgdown does, which is to have template functions (e.g. `pkgdown::template_articles()`), like `template_blogdown_post()` etc and more general `template_blogdown_archetype(archetype = "")` that pulls from the theme directory as you suggest. Then, I'll cram it into the ymlthis format and handle the issues you bring up as described above. The reason I think this might work well for it vs. the build-it-up approach is because pkgdown also lays out the explicit options given your set-up (in that case, the files in your package, and in the case of blogdown, your theme)

Thoughts? The names are open to adjustment as well :)

I also need to look at the blogdown add-in more closely. 

cc @rich-iannone if he has any thoughts

**Comment by malcolmbarrett** [comment]
oh jeez, these archetype files (at least the academic theme ones) are in TOML

EDIT: They are TOML on my computer and YAML on the link you posted 🤔. Looks like they were converted to YAML earlier this year: https://github.com/gcushen/hugo-academic/commit/7cb7e497f75e016d772a002aea8edebbf72e5afe#diff-de1dfbd4dc5c4314c4b54d2eeabe880a

**Comment by apreshill** [comment]
Well but only for that theme- he converted I think partially due to blogdown users having more familiarity with YAML. See the Hugo convert function here: https://github.com/rstudio/blogdown/blob/master/R/hugo.R

**Comment by malcolmbarrett** [comment]
Ah, that might be helpful. A first pass at working with this does let me translate to YAML, but I don't know how extensible/safe this is

```r
fs::dir_copy(file.path("themes", "hugo-academic", "archetypes"), tempdir())
 
readr::read_file(file.path(tempdir(), "post.md")) %>% 
  #  has trouble with these {{}} templates
  stringr::str_replace_all('\\{\\{.+\\}\\}', '\\"\\"') %>% 
  stringr::str_replace_all('\\"\\"\\"\\"', '\\"\\"') %>% 
  readr::write_lines(file.path(tempdir(), "post-clean.md"))

blogdown:::hugo_toYAML(file.path(tempdir(), "post-clean.md"))
post_yml <- yaml::yaml.load_file(file.path(tempdir(), "post-clean.md")) %>% 
  ymlthis::as_yml()

post_yml

# ---
# categories: []
# date: ''
# draft: false
# header:
#   caption: ''
#   image: ''
#   preview: true
# tags: []
# title: ''
# ---

fs::dir_delete(tempdir())
```

**Comment by malcolmbarrett** [comment]
I added a more robust version that checks for themes and archetypes to ymlthis, as well as a function that returns available archetypes. `blogdown_template()` returns a `yml` object so can be modified with `yml_*()` or manipulated with `yml_drop()` and `yml_replace()`.

```r
blogdown_template("post")

# ---
# categories: []
# date: ''
# draft: false
# header:
#   caption: ''
#   image: ''
#   preview: true
# tags: []
# title: ''
# ---

blogdown_archetypes()
# [1] "default"     "home"        "post"        "project"     "publication" "talk"   
```

A skim through Hugo themes reveals a wide, wide variety in available archetypes, so I'm not sure what's best in terms of creating something like `blogdown_template_post()`

**Comment by malcolmbarrett** [comment]
I'm going to close this; thanks for the tips & let me know if you have other suggestions re: blogdown!

**Comment by batpigandme** [comment]
Posting here bc I _think_ you've answered above re. adding a generic `yml_toplevel()` instead; but I'm curious if handling `<taxonomies>` (from Hugo's [front matter docs](https://gohugo.io/content-management/front-matter/)) to blogdown in `yml_blogdown_opts()` is going to need different treatment than a "regular" user-defined because of Hugo site config ([Configure Taxonomies | Hugo](https://gohugo.io/content-management/taxonomies#configuring-taxonomies)).

If yes, I can work on a helper for this as we re-configure the tidyverse site.

**Comment by malcolmbarrett** [comment]
Hmm I'm not that familiar with custom taxonomies (just watched the YouTube video on the doc page 😜), but it looks like it gets specified in the config file then is just used in the top level of the YAML as with `tags` and `categories`, right? `yml_blogdown_opts()` has a `...` option, so you could just write it at once (using the moods taxonomy example from the video):

```r
yml_empty() %>% yml_blogdown_opts(draft = TRUE, moods = "upbeat")
#> ---
#> draft: true
#> moods: upbeat
#> ---
```

Is that what you're looking for? If there are some other subtleties to it, though, would love a helper!

**Comment by batpigandme** [comment]
Cool. I'll see how it goes. I think there's a way to add a predefined list of taxonomies to the site config, but dynamically updating that could get gross. 
I'm also beginning to think it's theme dependent, so `...` might be the best course.

**Comment by malcolmbarrett** [comment]
Let me know if you bump into anything that should be included here! Seems like the funkiness is primarily in how you have to specify it in the config file, but customizing hugo is still pretty new to me
